# Generated by Django 5.1.6 on 2025-09-10 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_notes', '0002_add_search_triggers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
