# Generated by Django 5.1.6 on 2025-09-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_notes', '0004_usernotelibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
