# Generated by Django 5.1.6 on 2025-09-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_notes', '0005_note_is_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='is_publish',
            field=models.BooleanField(default=True),
        ),
    ]
