# Generated by Django 5.1.6 on 2025-10-01 15:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_notes', '0006_alter_note_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='notechatlog',
            name='session_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
