# Generated by Django 5.1.6 on 2025-09-06 06:18

import apis.api_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=apis.api_auth.models.default_expiry),
        ),
    ]
