# Generated by Django 5.1.6 on 2025-09-05 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('reminder_minutes_before', models.PositiveIntegerField(blank=True, null=True)),
                ('want_notification', models.BooleanField(default=False)),
                ('reminder_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('done', 'Done'), ('skipped', 'Skipped')], default='planned', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time', 'id'],
                'indexes': [models.Index(fields=['user', 'date'], name='api_planner_user_id_cc3d2f_idx'), models.Index(fields=['status', 'date'], name='api_planner_status_f64876_idx')],
            },
        ),
    ]
