# Generated by Django 5.1.6 on 2025-09-05 17:39

import apis.api_payment.models
import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChainCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ok', 'OK (Intact)'), ('broken', 'Broken (Tampering Detected)'), ('error', 'Error During Verification')], db_index=True, max_length=16)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('checked_by', models.CharField(blank=True, default='system', max_length=64)),
                ('details', models.TextField(blank=True, default='')),
                ('last_verified_log_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['status', 'checked_at'], name='idx_chaincheck_status_date')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[apis.api_payment.models.validate_positive_amount])),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=12)),
                ('payment_method', models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('wallet', 'Wallet')], max_length=20)),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('order_id', models.CharField(blank=True, max_length=128, null=True)),
                ('description', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('gateway_status', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('payment_create', 'Payment Create'), ('payment_capture', 'Payment Capture'), ('refund_request', 'Refund Request'), ('refund_execute', 'Refund Execute')], max_length=32)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=10)),
                ('message', models.TextField(blank=True, default='')),
                ('ip_address_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('user_agent_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('request_id_hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('refund_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('prev_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('entry_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[apis.api_payment.models.validate_positive_amount])),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('refund_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('reason', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='api_payment.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'created_at'], name='idx_payment_user_date'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_id'], name='idx_payment_payment_id'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refund_id'], name='idx_refund_refund_id'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment', 'created_at'], name='idx_refund_payment_date'),
        ),
    ]
