# Generated by Django 5.1.6 on 2025-09-10 04:10

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', encrypted_model_fields.fields.EncryptedTextField()),
                ('summary', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('mood', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('themes', models.JSONField(blank=True, null=True)),
                ('suggestions', models.JSONField(blank=True, null=True)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JournalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='journal_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api_journal.journal')),
            ],
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['user', 'created_at'], name='api_journal_user_id_d57d56_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['mood'], name='api_journal_mood_a28faa_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='api_journal_search__dc54f8_gin'),
        ),
    ]
